print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/flan/Desktop/Unity/final-corpse/finalCorpse-master/Assets/RICK SAYS 'DO NOT OPEN'/models/scratch.mb"`)
{		
	file -o "/Users/flan/Desktop/Unity/final-corpse/finalCorpse-master/Assets/RICK SAYS 'DO NOT OPEN'/models/scratch.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/flan/Desktop/Unity/final-corpse/finalCorpse-master/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/flan/Desktop/Unity/final-corpse/finalCorpse-master/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/flan/Desktop/Unity/final-corpse/finalCorpse-master/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
